#!/bin/bash
#Script by Kris Occhipinti
#http://filmsbykris.com
#GPLv3 - http://www.gnu.org/licenses/gpl-3.0.txt
#Source code https://github.com/metalx1000/Video-and-Film-Scripts
#This Script is designed to trim and combine all video clips in a folder

if [ $# -lt 3 ]
then
    echo "Useage: $0 <file type> <speed> <output dir>"
    echo "Example: $0 MOV 2 /tmp/output #double speed - 200%"
    exit 0
fi

ext=$1
speed=$2 #fade length in frames
outputdir="$3"
outputfile="${outputdir}/combine_$(date +%s).$ext"

echo "creating \"$outputdir\""
mkdir -p "$outputdir" || e="error"

if [ "$e" = "error" ]
then
    echo "Can't create $outputdir"
    exit 1
fi

x=""
for i in *.$ext
do 
    x="$x framebuffer:$i?$speed "
done

x="melt$x -consumer avformat:$outputfile acodec=mp2 ab=128k"

eval $x

mplayer $outputfile -fs
