#!/bin/bash
#Script by Kris Occhipinti
#http://filmsbykris.com
#GPLv3 - http://www.gnu.org/licenses/gpl-3.0.txt
#Source code https://github.com/metalx1000/Video-and-Film-Scripts
#This Script is designed to trim and combine all video clips in a folder

if [ $# -lt 3 ]
then
    echo "Useage: $0 <file type> <start frame> <number of frames> <output dir>"
    echo "Example: $0 MOV 30 120 /tmp/output"
    exit 0
fi

ext=$1
in=$2 #fade length in frames
out=$3
outputdir="$4"
outputfile="${outputdir}/trim_$(date +%s).$ext"

echo "creating \"$outputdir\""
mkdir -p "$outputdir" || e="error"

if [ "$e" = "error" ]
then
    echo "Can't create $outputdir"
    exit 1
fi

x=""
for i in *.$ext
do 
    x="$x $i in=$in out=$out "
done

x="melt$x -consumer avformat:$outputfile acodec=mp2 ab=128k"

eval $x

mplayer $outputfile
